# -*- coding: utf-8 -*-
"""sheebah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eG0JSwBWlS3Tf4gESUG_dTtk1VIDvJLS
"""

print("hello")

import pandas as pd
s=pd.Series()
print (s)

import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)
print(data)

import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data,index=[100,101,102,103])
print(s)
print(data)

import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data,index=[100,101,102])
print(s)
print(data)

import pandas as pd
import numpy as np
data=np.array(['a','b','c'])
s=pd.Series(data,index=[100,101,102,103])
print(s)
print(data)



import pandas as pd
s=pd.Series([1,2,3,4],index=['a','b','c','d'])
print (s['a'])

import pandas as pd
df=pd.DataFrame()
print(df)

import pandas as pd
data=['a','b','c','d']
df=pd.DataFrame(data)
print(df)

import pandas as pd
data=[['sheebah',10],['hi',12],['guve',13]]
df=pd.DataFrame(data,columns=['Name','age'])
print(df)

import pandas as pd
data=[['sheebah',10],['hi',12],['guve',13]]
df=pd.DataFrame(data,columns=['Name','age'],dtype=float)
print(df)

import pandas as pd
data={'year':[2010,2011,2012,2013],
     'team':['csk','mi','rcb','kkr'],
     'wins':[1,2,3,4],
    'losses':[2,3,4,5]}
ipl=pd.DataFrame(data)
print(ipl)

print(ipl.dtypes)

ipl.describe

print(ipl.describe())

print(ipl.boxplot())

print(ipl.info())

print((ipl.plot.line(y='wins')))

print(ipl.hist(bins=10))

ipl.shape

ipl.size

print(ipl.sort_values(by=["wins"],ascending=False))

print(ipl.columns[2])

print(ipl.iloc[1])

print(ipl.iloc[[1]])

print(ipl.iloc[[0,1,2,3]])

print(ipl.drop(columns='losses'))

print(ipl.drop(columns='wins'))

print(ipl['team'].unique())

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/titanic_train.csv")
df

print(df.plot.line(y='Survived'))

print(df.plot.pie(y='Survived'))

print(df.plot.pie(y='Pclass'))

d1=df["Sex"].replace("male",1)
d2=d1.replace("female",2)
d2

d3=d2.values
print(d3)

print(df.plot.pie(y="Sex"))

df["Survived"]

d1=df["Sex"].replace("male",1)
d1.replace("female",2)



print(df.hist(bins=10))

print(df.plot.line(y='Parch'))